### ISSUE TITLE
Error on updating to latest ESPHome 2023.12.0

### ISSUE THREAD

**Issue by florianmulatz** [Schluggi/AIOsense#152] opened 2023-12-21 05:55 UTC
**Category**
- [ ] Hardware / PCB
- [X] Software / ESPHome

**Version of ESPHome / AIOsense**
ESPHome 2023.12.0

**Describe the bug**
```
INFO ESPHome 2023.12.0
INFO Reading configuration /config/esphome/esphome-mmwave-wohnzimmer.yaml...
WARNING GPIO8 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO2 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

output.ledc: [source <unicode string>:4]
  
  Pin 0 is used in multiple places.
  platform: ledc
  pin: 
    number: 0
    mode: 
      output: True
      input: False
      open_drain: False
      pullup: False
      pulldown: False
    inverted: False
    ignore_strapping_warning: False
    drive_strength: 20.0
  id: rtttl_out
  zero_means_zero: False
  frequency: 1000.0
microphone.i2s_audio: [source <unicode string>:7]
  
  Pin 0 is used in multiple places.
  platform: i2s_audio
  id: mic_i2s
  channel: left
  i2s_din_pin: 0
  i2s_audio_id: i2s_in
  pdm: False
  bits_per_sample: 32.0
  adc_type: external
== [ERROR] /config/esphome/esphome-mmwave-wohnzimmer.yaml ==
```

**Comment by Schluggi** [comment] 2023-12-26 12:14
This is (kind of) by design. In V2.1.x the buzzer/beeper and the mic has the same pin so you have to choose what do you want to use. You can not use both at the same time. This will be fixed in V3.0.0.

**Closed by Schluggi** 2023-12-26 12:14 UTC
Labels: bug
